# Configuracion del Puerto
server.port=3001

# Configuracion de Base de Datos (H2)
spring.datasource.url=jdbc:h2:mem:recochadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

# Mostrar SQL en consola
spring.jpa.show-sql=true

# MongoDB Atlas
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://santiov22:sanalejo2211@cluster0.thnofc7.mongodb.net/recochapp?retryWrites=true&w=majority&appName=Cluster0}
spring.data.mongodb.auto-index-creation=true
